<a href="https://colab.research.google.com/github/Nasim-Amani/grid-failure/blob/main/content_daily_feeder_health(II).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# ==============================
# 1. Mount Google Drive
# ==============================

from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# ==============================
# 2. Import libraries
# ==============================

import os
import zipfile
import pandas as pd
import glob


# ==============================
# 3. Define paths
# ==============================

# Change this to your ZIP file location in Google Drive
zip_path = "/content/drive/MyDrive/feeders_DATA.zip"

# Where to extract the ZIP file
extract_path = "/content/extracted_dataset"


# ==============================
# 4. Extract ZIP file
# ==============================

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("ZIP extracted successfully!")


# ==============================
# 5. Find all XLSX files
# ==============================

xlsx_files = glob.glob(
    os.path.join(extract_path, "**/*.xlsx"),
    recursive=True
)

print(f"Number of Excel files found: {len(xlsx_files)}")

for file in xlsx_files:
    print(file)


# ==============================
# 6. Read all Excel files
# ==============================

dataframes = []

for file in xlsx_files:
    print(f"Reading: {file}")

    df = pd.read_excel(
        file,
        sheet_name=0   # read first sheet only
    )

    # Keep track of source file
    df["source_file"] = os.path.basename(file)

    dataframes.append(df)


# ==============================
# 7. Combine all files
# ==============================

data = pd.concat(
    dataframes,
    ignore_index=True
)


# ==============================
# 8. Basic inspection
# ==============================

print("\nDataset shape:")
print(data.shape)

print("\nFirst 5 rows:")
display(data.head())

print("\nColumn names:")
print(data.columns.tolist())

ZIP extracted successfully!
Number of Excel files found: 19
/content/extracted_dataset/DATA/1399-1.xlsx
/content/extracted_dataset/DATA/1402-2.xlsx
/content/extracted_dataset/DATA/1396-1.xlsx
/content/extracted_dataset/DATA/1403-2.xlsx
/content/extracted_dataset/DATA/1404-1-.xlsx
/content/extracted_dataset/DATA/1401-1.xlsx
/content/extracted_dataset/DATA/1398-2.xlsx
/content/extracted_dataset/DATA/1403-1.xlsx
/content/extracted_dataset/DATA/1395-1.xlsx
/content/extracted_dataset/DATA/1400-2.xlsx
/content/extracted_dataset/DATA/1396-2.xlsx
/content/extracted_dataset/DATA/1400-1.xlsx
/content/extracted_dataset/DATA/1402-1.xlsx
/content/extracted_dataset/DATA/1401-2.xlsx
/content/extracted_dataset/DATA/1395-2.xlsx
/content/extracted_dataset/DATA/1398-1.xlsx
/content/extracted_dataset/DATA/1399-2.xlsx
/content/extracted_dataset/DATA/1397-2.xlsx
/content/extracted_dataset/DATA/1397-1.xlsx
Reading: /content/extracted_dataset/DATA/1399-1.xlsx
Reading: /content/extracted_dataset/DATA/1402-2.xlsx
Reading: /content/extracted_dataset/DATA/1396-1.xlsx
Reading: /content/extracted_dataset/DATA/1403-2.xlsx
Reading: /content/extracted_dataset/DATA/1404-1-.xlsx
Reading: /content/extracted_dataset/DATA/1401-1.xlsx
Reading: /content/extracted_dataset/DATA/1398-2.xlsx
Reading: /content/extracted_dataset/DATA/1403-1.xlsx
Reading: /content/extracted_dataset/DATA/1395-1.xlsx
Reading: /content/extracted_dataset/DATA/1400-2.xlsx
Reading: /content/extracted_dataset/DATA/1396-2.xlsx
Reading: /content/extracted_dataset/DATA/1400-1.xlsx
Reading: /content/extracted_dataset/DATA/1402-1.xlsx
Reading: /content/extracted_dataset/DATA/1401-2.xlsx
Reading: /content/extracted_dataset/DATA/1395-2.xlsx
Reading: /content/extracted_dataset/DATA/1398-1.xlsx
Reading: /content/extracted_dataset/DATA/1399-2.xlsx
Reading: /content/extracted_dataset/DATA/1397-2.xlsx
Reading: /content/extracted_dataset/DATA/1397-1.xlsx

Dataset shape:
(2764, 55)

First 5 rows:

,ردیف,روز هفته,ردیف یکتا,معاونت,منطقه اصلی,تاریخ اطلاع,ساعت اطلاع,پست فوق توزیع,کد پست فوق توزیع,فیدر فشار متوسط,...,گزارش کار اکیپ,اجازه کار,موقعیت خطا,شرح موقعیت خطا,کاربر ثبت کننده,ترانس MV,ترانس LV,GISCODE پست توزیع,GISCODE فیدر فشار متوسط,source_file
0,42,دوشنبه,8330145,معاونت شمالشرق,پاسداران,1399/06/31,19:40:00,شريعتي,257.0,MV_شريعتي_شهرزاد,...,NaN,NaN,NaN,NaN,حسن الله ياري,NaN,NaN,E914@GP13080000C04E,112280,1399-1.xlsx
1,1120,چهارشنبه,8316137,معاونت شمالشرق,پاسداران,1399/06/26,12:49:00,شريعتي,257.0,MV_شريعتي_شهرزاد,...,NaN,NaN,NaN,NaN,حبيب کريمي نسب,NaN,NaN,E914@GP13130000C96E,112280,1399-1.xlsx
2,1459,سه شنبه,8311045,معاونت شمالشرق,پاسداران,1399/06/25,04:56:00,شريعتي,257.0,MV_شريعتي_شهرزاد,...,NaN,NaN,NaN,NaN,عظيمي بهادر,NaN,NaN,E914@GP13130000C96E,112280,1399-1.xlsx
3,1491,دوشنبه,8310676,معاونت شمالشرق,نیاوران,1399/06/24,21:51:00,شريعتي,257.0,MV_شريعتي_زمرد,...,NaN,NaN,NaN,NaN,حسين زينالي,NaN,NaN,E914@GP13130000C9B6,112240,1399-1.xlsx
4,1973,يکشنبه,8304780,معاونت شمالشرق,نیاوران,1399/06/23,09:50:00,شريعتي,257.0,MV_شريعتي_زمرد,...,NaN,NaN,NaN,NaN,عليرضا ابراهيمي,NaN,NaN,E914@GP13130004ECBE,112240,1399-1.xlsx

Column names:
['ردیف', 'روز هفته', 'ردیف یکتا', 'معاونت', 'منطقه اصلی', 'تاریخ اطلاع', 'ساعت اطلاع', 'پست فوق توزیع ', 'کد پست فوق توزیع', 'فیدر فشار متوسط', 'کد فیدر فشار متوسط', 'پست توزیع', 'کد پست توزیع', 'فیدر فشار ضعیف', 'آدرس', ' سطح ولتاژ', 'گروه قطع', 'علت قطع', 'اشکال', 'علت اشکال', 'جریان قطع اولیه', 'بار قطع شده (MWH)', 'انرژی توزیع نشده (KWH)', 'مدت قطع', ' جداکننده', 'نوع قطعی', 'وضعیت محل', 'مامور حوادث1', 'نوع بابرنامه', 'تکی یا کلی به تشخیص اپراتور', 'مامورحوادث2', 'زون ', 'منطقه 2', 'شرح حادثه', 'اطلاعات', 'زمان قطع', 'زمان وصل', 'مدت زمان خاموشی به دقیقه', 'كاربري كه ثبت كرده', 'نوع پست', 'نام پیمانکار', 'تلفن پیمانکار', 'مجموع تعداد کلیدزنی', 'گزارش دهنده', 'نوع سایر', 'گزارش کار اکیپ', 'اجازه کار', 'موقعیت خطا', 'شرح موقعیت خطا', 'کاربر ثبت کننده', 'ترانس MV', 'ترانس LV', 'GISCODE پست توزیع', 'GISCODE فیدر فشار متوسط', 'source_file']

In [3]:
# ==========================================
# Step 1: Dataset Column Evaluation
# ==========================================

import pandas as pd
import numpy as np


# Assuming your combined dataframe is called "data"
df = data.copy()


# ------------------------------------------
# Basic dataset information
# ------------------------------------------

print("="*80)
print("DATASET BASIC INFORMATION")
print("="*80)

print(f"Number of rows: {df.shape[0]:,}")
print(f"Number of columns: {df.shape[1]:,}")

print("\n")


# ------------------------------------------
# Column evaluation table
# ------------------------------------------

column_profile = pd.DataFrame({
    "Column": df.columns,
    "Data_Type": df.dtypes.astype(str),
    "Missing_Count": df.isna().sum().values,
    "Missing_Percentage": (
        df.isna().mean().values * 100
    ).round(2),
    "Unique_Count": [
        df[col].nunique(dropna=False)
        for col in df.columns
    ],
    "Sample_Value": [
        df[col].dropna().iloc[0]
        if df[col].notna().any()
        else "ALL_NULL"
        for col in df.columns
    ]
})


# Sort by missing percentage
column_profile = column_profile.sort_values(
    by="Missing_Percentage",
    ascending=False
)


display(column_profile)


# ------------------------------------------
# Duplicate rows
# ------------------------------------------

print("\n")
print("="*80)
print("DUPLICATE CHECK")
print("="*80)

duplicate_count = df.duplicated().sum()

print(f"Duplicate rows: {duplicate_count:,}")


# ------------------------------------------
# Columns with only one unique value
# ------------------------------------------

print("\n")
print("="*80)
print("CONSTANT COLUMNS")
print("="*80)

constant_columns = [
    col for col in df.columns
    if df[col].nunique(dropna=False) <= 1
]

if constant_columns:
    for col in constant_columns:
        print(col)
else:
    print("No constant columns found.")


# ------------------------------------------
# High cardinality columns
# ------------------------------------------

print("\n")
print("="*80)
print("HIGH CARDINALITY COLUMNS")
print("="*80)

high_cardinality = column_profile[
    column_profile["Unique_Count"] > 100
]

display(high_cardinality)


# ------------------------------------------
# Categorical column overview
# ------------------------------------------

print("\n")
print("="*80)
print("CATEGORICAL COLUMN SUMMARY")
print("="*80)


categorical_columns = df.select_dtypes(
    include=["object"]
).columns


for col in categorical_columns:

    print("\n")
    print("-"*60)
    print(f"Column: {col}")
    print(f"Unique values: {df[col].nunique(dropna=False)}")

    print(df[col]
          .value_counts(dropna=False)
          .head(10)
    )

================================================================================
DATASET BASIC INFORMATION
================================================================================
Number of rows: 2,764
Number of columns: 55

,Column,Data_Type,Missing_Count,Missing_Percentage,Unique_Count,Sample_Value
تلفن پیمانکار,تلفن پیمانکار,float64,2764,100.00,1,ALL_NULL
گزارش کار اکیپ,گزارش کار اکیپ,float64,2764,100.00,1,ALL_NULL
اطلاعات,اطلاعات,float64,2764,100.00,1,ALL_NULL
منطقه 2,منطقه 2,float64,2764,100.00,1,ALL_NULL
مامور حوادث1,مامور حوادث1,float64,2764,100.00,1,ALL_NULL
مامورحوادث2,مامورحوادث2,float64,2764,100.00,1,ALL_NULL
نوع بابرنامه,نوع بابرنامه,float64,2764,100.00,1,ALL_NULL
ترانس LV,ترانس LV,float64,2764,100.00,1,ALL_NULL
ترانس MV,ترانس MV,float64,2764,100.00,1,ALL_NULL
نام پیمانکار,نام پیمانکار,float64,2764,100.00,1,ALL_NULL
نوع سایر,نوع سایر,float64,2764,100.00,1,ALL_NULL
اجازه کار,اجازه کار,float64,2764,100.00,1,ALL_NULL
موقعیت خطا,موقعیت خطا,float64,2764,100.00,1,ALL_NULL
شرح موقعیت خطا,شرح موقعیت خطا,float64,2764,100.00,1,ALL_NULL
علت اشکال,علت اشکال,object,1762,63.75,55,اتصال نامناسب سرخط به شبكه
اشکال,اشکال,object,1575,56.98,117,قطع ترانسفورماتور یا کلید اصلی
زون,زون,object,1346,48.70,225,پاسداران
شرح حادثه,شرح حادثه,object,1189,43.02,1468,رفع اتصالي
فیدر فشار ضعیف,فیدر فشار ضعیف,float64,794,28.73,20,2.0
گزارش دهنده,گزارش دهنده,object,423,15.30,11,همـــــا
پست توزیع,پست توزیع,object,106,3.84,80,شهرزاد
GISCODE پست توزیع,GISCODE پست توزیع,object,106,3.84,80,E914@GP13080000C04E
کد پست توزیع,کد پست توزیع,object,106,3.84,2,
نوع پست,نوع پست,object,106,3.84,7,زمينى
آدرس,آدرس,object,94,3.40,2188,قبا
جداکننده,جداکننده,object,28,1.01,25,كليد فيدر
کد پست فوق توزیع,کد پست فوق توزیع,float64,10,0.36,2,257.0
پست فوق توزیع,پست فوق توزیع,object,10,0.36,2,شريعتي
بار قطع شده (MWH),بار قطع شده (MWH),float64,2,0.07,2377,0.0647
انرژی توزیع نشده (KWH),انرژی توزیع نشده (KWH),float64,2,0.07,2464,150.966825
جریان قطع اولیه,جریان قطع اولیه,float64,2,0.07,573,137.3333
وضعیت محل,وضعیت محل,object,1,0.04,2,روشن
ردیف,ردیف,int64,0,0.00,2703,42
روز هفته,روز هفته,object,0,0.00,7,دوشنبه
ردیف یکتا,ردیف یکتا,int64,0,0.00,2764,8330145
معاونت,معاونت,object,0,0.00,1,معاونت شمالشرق
منطقه اصلی,منطقه اصلی,object,0,0.00,2,پاسداران
تاریخ اطلاع,تاریخ اطلاع,object,0,0.00,1461,1399/06/31
ساعت اطلاع,ساعت اطلاع,object,0,0.00,1079,19:40:00
گروه قطع,گروه قطع,object,0,0.00,10,خطوط زميني فشارضعيف
سطح ولتاژ,سطح ولتاژ,object,0,0.00,4,فشار ضعيف
علت قطع,علت قطع,object,0,0.00,103,خاموشی بابرنامه جهت نصب و تعويض مفصل
فیدر فشار متوسط,فیدر فشار متوسط,object,0,0.00,4,MV_شريعتي_شهرزاد
کد فیدر فشار متوسط,کد فیدر فشار متوسط,int64,0,0.00,4,25794052
نوع قطعی,نوع قطعی,object,0,0.00,2,با برنامه
تکی یا کلی به تشخیص اپراتور,تکی یا کلی به تشخیص اپراتور,object,0,0.00,2,كلي
مدت قطع,مدت قطع,int64,0,0.00,214,140
كاربري كه ثبت كرده,كاربري كه ثبت كرده,object,0,0.00,141,حسن الله ياري
مدت زمان خاموشی به دقیقه,مدت زمان خاموشی به دقیقه,int64,0,0.00,214,140
زمان وصل,زمان وصل,object,0,0.00,1030,22:00:00
زمان قطع,زمان قطع,object,0,0.00,1079,19:40:00
مجموع تعداد کلیدزنی,مجموع تعداد کلیدزنی,int64,0,0.00,1,0
کاربر ثبت کننده,کاربر ثبت کننده,object,0,0.00,141,حسن الله ياري
GISCODE فیدر فشار متوسط,GISCODE فیدر فشار متوسط,int64,0,0.00,4,112280
source_file,source_file,object,0,0.00,19,1399-1.xlsx

================================================================================
DUPLICATE CHECK
================================================================================
Duplicate rows: 0


================================================================================
CONSTANT COLUMNS
================================================================================
معاونت
مامور حوادث1
نوع بابرنامه
مامورحوادث2
منطقه 2
اطلاعات
نام پیمانکار
تلفن پیمانکار
مجموع تعداد کلیدزنی
نوع سایر
گزارش کار اکیپ
اجازه کار
موقعیت خطا
شرح موقعیت خطا
ترانس MV
ترانس LV


================================================================================
HIGH CARDINALITY COLUMNS
================================================================================

,Column,Data_Type,Missing_Count,Missing_Percentage,Unique_Count,Sample_Value
اشکال,اشکال,object,1575,56.98,117,قطع ترانسفورماتور یا کلید اصلی
زون,زون,object,1346,48.70,225,پاسداران
شرح حادثه,شرح حادثه,object,1189,43.02,1468,رفع اتصالي
آدرس,آدرس,object,94,3.40,2188,قبا
بار قطع شده (MWH),بار قطع شده (MWH),float64,2,0.07,2377,0.0647
انرژی توزیع نشده (KWH),انرژی توزیع نشده (KWH),float64,2,0.07,2464,150.966825
جریان قطع اولیه,جریان قطع اولیه,float64,2,0.07,573,137.3333
ردیف,ردیف,int64,0,0.00,2703,42
ردیف یکتا,ردیف یکتا,int64,0,0.00,2764,8330145
تاریخ اطلاع,تاریخ اطلاع,object,0,0.00,1461,1399/06/31
ساعت اطلاع,ساعت اطلاع,object,0,0.00,1079,19:40:00
علت قطع,علت قطع,object,0,0.00,103,خاموشی بابرنامه جهت نصب و تعويض مفصل
مدت قطع,مدت قطع,int64,0,0.00,214,140
كاربري كه ثبت كرده,كاربري كه ثبت كرده,object,0,0.00,141,حسن الله ياري
مدت زمان خاموشی به دقیقه,مدت زمان خاموشی به دقیقه,int64,0,0.00,214,140
زمان وصل,زمان وصل,object,0,0.00,1030,22:00:00
زمان قطع,زمان قطع,object,0,0.00,1079,19:40:00
کاربر ثبت کننده,کاربر ثبت کننده,object,0,0.00,141,حسن الله ياري

================================================================================
CATEGORICAL COLUMN SUMMARY
================================================================================


------------------------------------------------------------
Column: روز هفته
Unique values: 7
روز هفته
دوشنبه      492
چهارشنبه    477
شنبه        461
يکشنبه      420
سه شنبه     397
پنجشنبه     302
جمعه        215
Name: count, dtype: int64


------------------------------------------------------------
Column: معاونت
Unique values: 1
معاونت
معاونت شمالشرق    2764
Name: count, dtype: int64


------------------------------------------------------------
Column: منطقه اصلی
Unique values: 2
منطقه اصلی
پاسداران    2298
نیاوران      466
Name: count, dtype: int64


------------------------------------------------------------
Column: تاریخ اطلاع
Unique values: 1461
تاریخ اطلاع
1402/05/07    11
1403/05/06    11
1398/04/22    11
1398/04/23    10
1398/04/24    10
1399/03/31    10
1404/04/30     9
1401/05/02     9
1401/04/22     8
1395/04/30     8
Name: count, dtype: int64


------------------------------------------------------------
Column: ساعت اطلاع
Unique values: 1079
ساعت اطلاع
12:00:00    15
11:05:00    14
13:00:00    12
10:45:00    11
11:15:00    11
12:30:00    11
14:25:00    10
11:00:00    10
13:35:00    10
11:30:00     9
Name: count, dtype: int64


------------------------------------------------------------
Column: پست فوق توزیع
Unique values: 2
پست فوق توزیع
شريعتي    2754
NaN         10
Name: count, dtype: int64


------------------------------------------------------------
Column: فیدر فشار متوسط
Unique values: 4
فیدر فشار متوسط
MV_شريعتي_زمرد            953
MV_شريعتي_شهرزاد          637
MV_شريعتي_حسينيه ارشاد    624
MV_شريعتي_بيات            550
Name: count, dtype: int64


------------------------------------------------------------
Column: پست توزیع
Unique values: 80
پست توزیع
زمرد               192
زبرجد              174
شاهين              145
کوکب               136
شهرزاد             130
عدل                120
استاديوم داوديه    118
حافظ               114
NaN                106
بهشت 1              94
Name: count, dtype: int64


------------------------------------------------------------
Column: کد پست توزیع
Unique values: 2
کد پست توزیع
       2658
NaN     106
Name: count, dtype: int64


------------------------------------------------------------
Column: آدرس
Unique values: 2188
آدرس
NaN                                        94
محدوده شرق استاديوم داوديه (شهيد كشوري)    19
خ شريعتي محدوده دوراهي قلهك                17
محدوده خ گل نبي وميدان فرخي                13
شريعتي خ قبابن بست طباطبايي6               13
خ شريعتي _بالاتر از ميرداماد_منظرنژاد53    10
پاسداران نگارستان چهارم28                  10
محدوده خ قبا وقسمتي ازخ پاسداران           10
شريعتي پائين تراز حسينيه ارشاد ک ويرا7     10
پاسداران نگارستان سوم12                     8
Name: count, dtype: int64


------------------------------------------------------------
Column:  سطح ولتاژ
Unique values: 4
 سطح ولتاژ
فشار ضعيف     2402
فشار متوسط     339
فوق توزيع       16
توليد            7
Name: count, dtype: int64


------------------------------------------------------------
Column: گروه قطع
Unique values: 10
گروه قطع
خطوط زميني فشارضعيف                   1018
طرف فشارضعيف پستهاي توزيع              775
خطوط هوائي فشارضعيف                    406
طرف فشار متوسط پست هاي توزيع زميني     227
انشعابات مشتركان                       203
شبكه فشار متوسط زميني                   92
فوق توزيع                               16
شبكه فشار متوسط هوائي                   12
طرف فشارمتوسط پستهاي توزيع هوائي         8
كمبود توليد                              7
Name: count, dtype: int64


------------------------------------------------------------
Column: علت قطع
Unique values: 103
علت قطع
عملكرد يا اشكال در كليد فيدر(فيوز دار) فشار ضعيف       578
اشكال درجعبه شالتر                                     459
اتصالي كابل فشار ضعيف                                  111
اشكال در لوازم اندازه گيري مشتركين غيرديماندي تكفاز     98
خاموشی بابرنامه جهت اجراي طرح                           93
خاموشی بدلیل تعمیرات                                    83
سرويس دوره‌اي                                           82
سرقت تجهيزات                                            76
خاموشی بابرنامه جهت اصلاح شالتر                         74
عملكرد يا اشكال در كليد اصلي                            61
Name: count, dtype: int64


------------------------------------------------------------
Column: اشکال
Unique values: 117
اشکال
NaN                                                                                          1575
سوختن فيوز يك فازكليد فيدر(فيوز دار)                                                          247
سوختن يك فيوز يا پايه فيوزيا پدیده كابلشو سوختگي در يك فاز از جعبه شالتر با فيوز 250 آمپر     212
سوختن يك فيوز يا پايه فيوزيا پدیده كابلشو سوختگي در يك فاز از جعبه شالتر با فيوز 100 آمپر      58
سوختگي فيوز كنتور                                                                              56
سوختگي سرخط هوايي                                                                              43
قطع ترانسفورماتور یا کلید اصلی                                                                 42
اتصالي يك فاز به زمين                                                                          37
قطع سیم ارتباط و یا قطع کلید محدود کننده ورودی کنتور                                           30
قطع حفاظتي كليد                                                                                28
Name: count, dtype: int64


------------------------------------------------------------
Column: علت اشکال
Unique values: 55
علت اشکال
NaN                       1762
‌اضافه بار                 176
اضافه بار                  154
اضافه بار يا عدم تعادل     138
فرسودگي                    118
اتصالات سست                 67
نامناسب بودن حفاظت          52
عيب نامشخص                  46
عيب گذرا                    43
سستي اتصالات                27
Name: count, dtype: int64


------------------------------------------------------------
Column:  جداکننده
Unique values: 25
 جداکننده
كليد فيدر                993
كليد اصلي - كليد فيدر    847
جعبه 25×3                199
سکسیونر فیوز دار         147
كليد اصلي                 99
جمپر                      84
بريکر پست فوق توزيع       59
جعبه 200×3                53
شالتر 3×250               47
رگلوزر                    46
Name: count, dtype: int64


------------------------------------------------------------
Column: نوع قطعی
Unique values: 2
نوع قطعی
بی برنامه    1930
با برنامه     834
Name: count, dtype: int64


------------------------------------------------------------
Column: وضعیت محل
Unique values: 2
وضعیت محل
روشن    2763
NaN        1
Name: count, dtype: int64


------------------------------------------------------------
Column: تکی یا کلی به تشخیص اپراتور
Unique values: 2
تکی یا کلی به تشخیص اپراتور
كلي    1933
تكي     831
Name: count, dtype: int64


------------------------------------------------------------
Column: زون
Unique values: 225
زون
NaN                                                    1346
پاسداران                                                259
جنوب دولت خيابان دروس وارسته کماسايي تا نيستان3 - 3     259
3                                                       147
ميرداماد جنوب تا همت  - 6                               110
شمال ميرداماد تا ظفر نفت شمس تبريزي شمالي بهروز - 5      69
1                                                        62
خيابان پاسداران از دولت تا همت غرب - 10                  51
شمال خيابان دولت از بلوار کاوه تا شريعتي - 2             38
نياوران                                                  30
Name: count, dtype: int64


------------------------------------------------------------
Column: شرح حادثه
Unique values: 1468
شرح حادثه
NaN                                                                                                                1189
.                                                                                                                    33
گزارش خاموشی از مرکز تماس                                                                                            24
گزارش خاموشي از مرکز تماس                                                                                             9
گزارش خاموشی از مرکز تماس (اضافه شده توسط اکیپ): گزارش خاموشی از مرکز تماس                                            6
                                                                                                                      6
فاز از سر تیر                                                                                                         4
قطع فیوز ورودی تابلو                                                                                                  3
تعویض فیدر                                                                                                            3
جوشکاری شینه های تابلو فشار ضعیف و جوشکاری پیچ های کلید کل فشار ضعیف جهت سرقت شینه های مسی تابلو و سرقت کلید کل       3
Name: count, dtype: int64


------------------------------------------------------------
Column: زمان قطع
Unique values: 1079
زمان قطع
12:00:00    15
11:05:00    14
13:00:00    12
10:45:00    11
11:15:00    11
12:30:00    11
14:25:00    10
11:00:00    10
13:35:00    10
11:30:00     9
Name: count, dtype: int64


------------------------------------------------------------
Column: زمان وصل
Unique values: 1030
زمان وصل
13:00:00    18
11:00:00    17
14:00:00    17
12:00:00    14
11:45:00    13
14:20:00    13
12:45:00    12
11:20:00    12
12:20:00    11
10:40:00    11
Name: count, dtype: int64


------------------------------------------------------------
Column: كاربري كه ثبت كرده
Unique values: 141
كاربري كه ثبت كرده
حجت مومني         1172
SERVICEUSER        262
PrawAgentUser      217
Admin              197
حسن الله ياري       67
حبيب کريمي نسب      42
علي ميرزائي         41
ياسين شالچي         38
بهزاد موسي پور      30
علي همتي            21
Name: count, dtype: int64


------------------------------------------------------------
Column: نوع پست
Unique values: 7
نوع پست
زمينى       1900
زيرزمينى     443
كيوسك        248
NaN          106
هوايى         56
پد مانتد       6
پاساژ          5
Name: count, dtype: int64


------------------------------------------------------------
Column: گزارش دهنده
Unique values: 11
گزارش دهنده
مشترک           1638
همـــــا         544
NaN              423
سرويس             73
عمومی             59
همکار             10
آتش نشانی          7
شهرداری            5
مراکز درمانی       3
پلیس               1
Name: count, dtype: int64


------------------------------------------------------------
Column: کاربر ثبت کننده
Unique values: 141
کاربر ثبت کننده
حجت مومني         1172
SERVICEUSER        262
PrawAgentUser      217
Admin              197
حسن الله ياري       67
حبيب کريمي نسب      42
علي ميرزائي         41
ياسين شالچي         38
بهزاد موسي پور      30
علي همتي            21
Name: count, dtype: int64


------------------------------------------------------------
Column: GISCODE پست توزیع
Unique values: 80
GISCODE پست توزیع
E914@GP13130000C974    192
E914@GP13130000C9B6    174
E914@GP13070000D47A    145
E914@GP13130004ECBE    136
E914@GP13080000C04E    130
E914@GP13130000C96E    120
E914@GP13080000C043    118
E914@GP13080000C057    114
NaN                    106
E914@GP1307000432FC     94
Name: count, dtype: int64


------------------------------------------------------------
Column: source_file
Unique values: 19
source_file
1403-1.xlsx     313
1398-1.xlsx     279
1401-1.xlsx     225
1400-1.xlsx     202
1402-1.xlsx     196
1399-1.xlsx     188
1404-1-.xlsx    177
1397-1.xlsx     144
1395-1.xlsx     117
1401-2.xlsx     116
Name: count, dtype: int64

** The results show several important things: **

### Good points ✅
- Dataset size is manageable: **2764 rows × 55 columns** → easy to experiment with.
- No duplicate rows detected.
- We have the key prediction variables:
  - Feeder ID (`GISCODE فیدر فشار متوسط`)
  - Outage type (`نوع قطعی`)
  - Time information
  - Impact metrics (`انرژی توزیع نشده`, duration)
  - Causes and operational features

### Immediate cleaning decisions:
1. **Drop completely empty columns**  
   Many columns are 100% missing (e.g., `ترانس MV`, `ترانس LV`, `مامور حوادث`, `گزارش کار اکیپ`). They add no information.

2. **Remove constant columns**
   Example:
   - `معاونت` (only one value)
   - `مجموع تعداد کلیدزنی` (only one value = 0)  
   They cannot help ML.

3. **Keep high-value columns**
   Especially:
   - `GISCODE فیدر فشار متوسط`
   - `کد فیدر فشار متوسط`
   - `نوع قطعی`
   - `علت قطع`
   - `علت اشکال`
   - `اشکال`
   - `مدت زمان خاموشی`
   - `انرژی توزیع نشده`
   - `بار قطع شده`
   - `جریان قطع اولیه`
   - `جداکننده`
   - Location features

4. **Be careful with leakage**
   Do not directly use:
   - `زمان وصل`
   - `مدت قطع`
   - `شرح حادثه`
   - final fault descriptions

   for predicting the same outage. They should only become historical features later.

### One important observation:
Your feeder dimension is actually very good:
- Only **4 MV feeders**
- 80 distribution substations
- 19 yearly files

This means the next challenge is not huge-scale ML; it is **creating meaningful feeder health history**.


**Step 2: Clean column names + remove useless columns + normalize Persian text values.**

In [4]:
# ==========================================
# Step 2: Basic Cleaning
# ==========================================

import pandas as pd


# Copy original data
df_clean = data.copy()


# ------------------------------------------
# 1. Clean column names
# ------------------------------------------

df_clean.columns = (
    df_clean.columns
    .str.strip()
)


# ------------------------------------------
# 2. Normalize Persian characters
# ------------------------------------------

def normalize_persian(text):

    if isinstance(text, str):

        text = (
            text
            .replace("ي", "ی")
            .replace("ى", "ی")
            .replace("ك", "ک")
            .replace("ۀ", "ه")
            .strip()
        )

    return text


df_clean = df_clean.map(
    normalize_persian
)


# ------------------------------------------
# 3. Replace empty strings with NaN
# ------------------------------------------

df_clean = df_clean.replace(
    r'^\s*$',
    pd.NA,
    regex=True
)


# ------------------------------------------
# 4. Remove completely empty columns
# ------------------------------------------

empty_cols = df_clean.columns[
    df_clean.isna().all()
]

df_clean = df_clean.drop(
    columns=empty_cols
)


# ------------------------------------------
# 5. Remove constant columns
# ------------------------------------------

constant_cols = [
    col for col in df_clean.columns
    if df_clean[col].nunique(dropna=True) <= 1
]


df_clean = df_clean.drop(
    columns=constant_cols
)


# ------------------------------------------
# 6. Check result
# ------------------------------------------

print("Original shape:", data.shape)
print("Cleaned shape :", df_clean.shape)


print("\nCompletely empty columns removed:")
for col in empty_cols:
    print("-", col)


print("\nConstant columns removed:")
for col in constant_cols:
    print("-", col)


print("\nRemaining columns:")
print(df_clean.columns.tolist())

Original shape: (2764, 55)
Cleaned shape : (2764, 35)

Completely empty columns removed:
- کد پست توزیع
- مامور حوادث1
- نوع بابرنامه
- مامورحوادث2
- منطقه 2
- اطلاعات
- نام پیمانکار
- تلفن پیمانکار
- نوع سایر
- گزارش کار اکیپ
- اجازه کار
- موقعیت خطا
- شرح موقعیت خطا
- ترانس MV
- ترانس LV

Constant columns removed:
- معاونت
- پست فوق توزیع
- کد پست فوق توزیع
- وضعیت محل
- مجموع تعداد کلیدزنی

Remaining columns:
['ردیف', 'روز هفته', 'ردیف یکتا', 'منطقه اصلی', 'تاریخ اطلاع', 'ساعت اطلاع', 'فیدر فشار متوسط', 'کد فیدر فشار متوسط', 'پست توزیع', 'فیدر فشار ضعیف', 'آدرس', 'سطح ولتاژ', 'گروه قطع', 'علت قطع', 'اشکال', 'علت اشکال', 'جریان قطع اولیه', 'بار قطع شده (MWH)', 'انرژی توزیع نشده (KWH)', 'مدت قطع', 'جداکننده', 'نوع قطعی', 'تکی یا کلی به تشخیص اپراتور', 'زون', 'شرح حادثه', 'زمان قطع', 'زمان وصل', 'مدت زمان خاموشی به دقیقه', 'كاربري كه ثبت كرده', 'نوع پست', 'گزارش دهنده', 'کاربر ثبت کننده', 'GISCODE پست توزیع', 'GISCODE فیدر فشار متوسط', 'source_file']

## Basic Cleaning

This step removes obvious data quality problems:

- Remove empty columns with no information
- Remove constant columns with only one value
- Normalize Persian characters
- Replace empty strings with missing values

A final constant-column check is needed later because some columns may become constant after additional preprocessing.

In [5]:
# ==========================================
# Step 3: Target Creation + Date Inspection
# ==========================================

import pandas as pd


# Work on cleaned dataframe
df = df_clean.copy()


# ------------------------------------------
# 1. Inspect date and time format
# ------------------------------------------

print("Example date values:")
print(df["تاریخ اطلاع"].head())

print("\nExample time values:")
print(df["ساعت اطلاع"].head())


# ------------------------------------------
# 2. Inspect outage types
# ------------------------------------------

print("\nOutage type distribution:")

print(
    df["نوع قطعی"]
    .value_counts(dropna=False)
)


# ------------------------------------------
# 3. Create event-level failure target
# ------------------------------------------

target_map = {
    "بی برنامه": 1,
    "با برنامه": 0
}


df["failure_target"] = (
    df["نوع قطعی"]
    .map(target_map)
)


# Check for unexpected categories
unexpected_target = df["failure_target"].isna().sum()

print("\nUnmapped / missing target values:")
print(unexpected_target)


print("\nTarget distribution:")
print(
    df["failure_target"]
    .value_counts(dropna=False)
)


# ------------------------------------------
# 4. Check important columns
# ------------------------------------------

important_cols = [
    "GISCODE فیدر فشار متوسط",
    "کد فیدر فشار متوسط",
    "نوع قطعی",
    "مدت زمان خاموشی به دقیقه",
    "انرژی توزیع نشده (KWH)",
    "failure_target"
]


print("\nImportant column check:")

display(
    df[important_cols].head()
)


# ------------------------------------------
# 5. Missing values summary
# ------------------------------------------

print("\nMissing values:")

display(
    df.isna()
    .sum()
    .sort_values(ascending=False)
    .head(15)
)

Example date values:
0    1399/06/31
1    1399/06/26
2    1399/06/25
3    1399/06/24
4    1399/06/23
Name: تاریخ اطلاع, dtype: object

Example time values:
0    19:40:00
1    12:49:00
2    04:56:00
3    21:51:00
4    09:50:00
Name: ساعت اطلاع, dtype: object

Outage type distribution:
نوع قطعی
بی برنامه    1930
با برنامه     834
Name: count, dtype: int64

Unmapped / missing target values:
0

Target distribution:
failure_target
1    1930
0     834
Name: count, dtype: int64

Important column check:

,GISCODE فیدر فشار متوسط,کد فیدر فشار متوسط,نوع قطعی,مدت زمان خاموشی به دقیقه,انرژی توزیع نشده (KWH),failure_target
0,112280,25794052,با برنامه,140,150.966825,0
1,112280,25794052,با برنامه,73,75.661390,0
2,112280,25794052,بی برنامه,66,0.000000,1
3,112240,25794022,بی برنامه,82,88.208806,1
4,112240,25794022,با برنامه,99,33.943980,0

Missing values:

علت اشکال                 1762
اشکال                     1575
زون                       1347
شرح حادثه                 1199
فیدر فشار ضعیف             794
گزارش دهنده                423
نوع پست                    106
پست توزیع                  106
GISCODE پست توزیع          106
آدرس                        94
جداکننده                    28
بار قطع شده (MWH)            2
جریان قطع اولیه              2
انرژی توزیع نشده (KWH)       2
روز هفته                     0
dtype: int64

## Step 3: Date Conversion + Target Creation

This step prepares the data for prediction.

Actions performed:

1. Create a combined datetime column:
- Merge outage date and time information into one column.
- Keep it as text temporarily because Persian date conversion is not done yet.

2. Create the prediction target:
- Convert outage type into a binary target:
    - Unplanned outage (بی برنامه) → 1
    - Planned outage (با برنامه) → 0

3. Check important features:
- Verify feeder identifiers
- Check outage impact variables
- Confirm the new target column

4. Review missing values:
- Identify incomplete columns before modeling.
- Missing values are mostly expected because some information is only recorded for specific outage types.

Important observations:
- The target is imbalanced but acceptable:
    - Unplanned failures: 1930 (~70%)
    - Planned outages: 834 (~30%)

- Missing engineering information (fault details, zone, incident description) should not be removed immediately.
  Later:
    - categorical missing values → "Unknown"
    - numerical missing values → appropriate filling strategy

- Only 4 MV feeders exist in the dataset.
  This supports creating feeder health timelines for prediction.

In [6]:
# ==========================================
# Step 4: Jalali Date Conversion + Time Features
# ==========================================

!pip install persiantools -q

import pandas as pd
from persiantools.jdatetime import JalaliDate


df = df.copy()


# ------------------------------------------
# 1. Convert Jalali date to Gregorian
# ------------------------------------------

def convert_jalali_date(date):

    try:
        y, m, d = map(
            int,
            str(date).split("/")
        )

        return JalaliDate(
            y, m, d
        ).to_gregorian()

    except Exception:
        return pd.NaT


df["date_gregorian"] = pd.to_datetime(
    df["تاریخ اطلاع"].apply(convert_jalali_date),
    errors="coerce"
)


# ------------------------------------------
# 2. Create datetime
# ------------------------------------------

df["datetime"] = (
    df["date_gregorian"]
    +
    pd.to_timedelta(
        df["ساعت اطلاع"].astype(str),
        errors="coerce"
    )
)


# ------------------------------------------
# 3. Gregorian calendar features
# ------------------------------------------

df["gregorian_year"] = df["datetime"].dt.year
df["gregorian_month"] = df["datetime"].dt.month
df["gregorian_day"] = df["datetime"].dt.day

df["hour"] = df["datetime"].dt.hour


# ------------------------------------------
# 4. Iranian weekday
# ------------------------------------------

# Pandas:
# Monday = 0 ... Sunday = 6

df["weekday"] = df["datetime"].dt.weekday


# Iran:
# Saturday = 0 ... Friday = 6

df["iran_weekday"] = (
    (df["weekday"] + 2) % 7
)


iran_weekday_names = {
    0: "Saturday",
    1: "Sunday",
    2: "Monday",
    3: "Tuesday",
    4: "Wednesday",
    5: "Thursday",
    6: "Friday"
}


df["iran_weekday_name"] = (
    df["iran_weekday"]
    .map(iran_weekday_names)
)


# ------------------------------------------
# 5. Jalali calendar features
# ------------------------------------------

def extract_jalali_parts(jalali_date):

    try:

        y, m, d = map(
            int,
            str(jalali_date).split("/")
        )

        return pd.Series(
            [y, m, d]
        )

    except Exception:

        return pd.Series(
            [pd.NA, pd.NA, pd.NA]
        )


df[
    [
        "jalali_year",
        "jalali_month",
        "jalali_day"
    ]
] = (
    df["تاریخ اطلاع"]
    .apply(extract_jalali_parts)
)


# ------------------------------------------
# 6. Jalali season
# ------------------------------------------

def get_jalali_season(month):

    if month in [1, 2, 3]:
        return "Spring"

    elif month in [4, 5, 6]:
        return "Summer"

    elif month in [7, 8, 9]:
        return "Autumn"

    elif month in [10, 11, 12]:
        return "Winter"

    return "Unknown"


df["jalali_season"] = (
    df["jalali_month"]
    .apply(get_jalali_season)
)


# ------------------------------------------
# 7. Check result
# ------------------------------------------

print("Jalali season distribution:")

display(
    df["jalali_season"]
    .value_counts(dropna=False)
)


print("\nDate conversion examples:")

display(
    df[
        [
            "تاریخ اطلاع",
            "ساعت اطلاع",
            "date_gregorian",
            "datetime",
            "gregorian_year",
            "gregorian_month",
            "jalali_year",
            "jalali_month",
            "jalali_season",
            "hour",
            "iran_weekday_name"
        ]
    ].head()
)


print("\nDatetime missing values:")
print(
    df["datetime"]
    .isna()
    .sum()
)


print("\nNew dataframe shape:")
print(df.shape)

Jalali season distribution:

jalali_season
Summer    1360
Spring     592
Winter     438
Autumn     374
Name: count, dtype: int64

Date conversion examples:

,تاریخ اطلاع,ساعت اطلاع,date_gregorian,datetime,gregorian_year,gregorian_month,jalali_year,jalali_month,jalali_season,hour,iran_weekday_name
0,1399/06/31,19:40:00,2020-09-21,2020-09-21 19:40:00,2020,9,1399,6,Summer,19,Monday
1,1399/06/26,12:49:00,2020-09-16,2020-09-16 12:49:00,2020,9,1399,6,Summer,12,Wednesday
2,1399/06/25,04:56:00,2020-09-15,2020-09-15 04:56:00,2020,9,1399,6,Summer,4,Tuesday
3,1399/06/24,21:51:00,2020-09-14,2020-09-14 21:51:00,2020,9,1399,6,Summer,21,Monday
4,1399/06/23,09:50:00,2020-09-13,2020-09-13 09:50:00,2020,9,1399,6,Summer,9,Sunday

Datetime missing values:
0

New dataframe shape:
(2764, 49)

## Step 4: Jalali Date Conversion + Time Features

This step converts outage dates into a usable time format and creates calendar features.

Actions performed:
- Convert Jalali dates to Gregorian dates.
- Create a datetime column by combining date and outage time.
- Extract time features:
  - Gregorian year/month/day
  - Jalali year/month/day
  - Jalali season
  - Iranian weekday
  - Hour information

Purpose:
- Enable correct chronological ordering of feeder history.
- Capture seasonal and calendar patterns in outage behavior.
- Prepare temporal features for future predictive modeling.

Validation:
- No missing datetime values were detected.
- Time features were successfully created.

In [8]:
# ==========================================
# Final Check Before Aggregation
# ==========================================

# Create reference dataframe
df_reference = df.copy()


# ------------------------------------------
# 1. Sort feeder events chronologically
# ------------------------------------------

df_reference = (
    df_reference
    .sort_values(
        by=[
            "GISCODE فیدر فشار متوسط",
            "datetime"
        ]
    )
    .reset_index(drop=True)
)


# ------------------------------------------
# 2. Final dataset check
# ------------------------------------------

print("=" * 60)
print("REFERENCE DATASET SUMMARY")
print("=" * 60)


print("\nShape:")
print(df_reference.shape)


print("\nDate range:")
print(
    df_reference["datetime"].min(),
    "to",
    df_reference["datetime"].max()
)


print("\nNumber of MV feeders:")
print(
    df_reference["GISCODE فیدر فشار متوسط"]
    .nunique()
)


print("\nTarget distribution:")
display(
    df_reference["failure_target"]
    .value_counts()
)


print("\nMissing datetime values:")
print(
    df_reference["datetime"]
    .isna()
    .sum()
)


# ------------------------------------------
# 3. Check important columns are preserved
# ------------------------------------------

important_preserved_cols = [
    "منطقه اصلی",
    "زون",
    "پست توزیع",
    "GISCODE پست توزیع",
    "نوع پست",
    "سطح ولتاژ",
    "فیدر فشار ضعیف"
]


print("\nImportant categorical/network columns:")

for col in important_preserved_cols:

    if col in df_reference.columns:
        print("✓", col)

    else:
        print("MISSING:", col)


print("\nReady for aggregation.")

============================================================
REFERENCE DATASET SUMMARY
============================================================

Shape:
(2764, 49)

Date range:
2016-03-24 10:52:00 to 2025-09-20 10:26:00

Number of MV feeders:
4

Target distribution:

failure_target
1    1930
0     834
Name: count, dtype: int64

Missing datetime values:
0

Important categorical/network columns:
✓ منطقه اصلی
✓ زون
✓ پست توزیع
✓ GISCODE پست توزیع
✓ نوع پست
✓ سطح ولتاژ
✓ فیدر فشار ضعیف

Ready for aggregation.

In [9]:
# ==========================================
# Rename columns to English names
# ==========================================

rename_map = {

    "ردیف": "row_id",
    "روز هفته": "reported_weekday_name",
    "ردیف یکتا": "event_id",

    "منطقه اصلی": "region",

    "تاریخ اطلاع": "report_date",
    "ساعت اطلاع": "report_time",

    "فیدر فشار متوسط": "mv_feeder",
    "کد فیدر فشار متوسط": "mv_feeder_code",

    "پست توزیع": "distribution_substation",
    "فیدر فشار ضعیف": "lv_feeder",

    "آدرس": "address",
    "سطح ولتاژ": "voltage_level",

    "گروه قطع": "outage_group",
    "علت قطع": "outage_reason",

    "اشکال": "fault_type",
    "علت اشکال": "fault_reason",

    "جریان قطع اولیه": "initial_current",

    "بار قطع شده (MWH)": "interrupted_load_mwh",
    "انرژی توزیع نشده (KWH)": "energy_not_supplied_kwh",

    "مدت قطع": "outage_duration",
    "جداکننده": "switch_device",

    "نوع قطعی": "outage_type",
    "تکی یا کلی به تشخیص اپراتور": "outage_scope",

    "زون": "zone",

    "شرح حادثه": "incident_description",

    "زمان قطع": "outage_start",
    "زمان وصل": "outage_end",

    "مدت زمان خاموشی به دقیقه": "outage_minutes",

    "كاربري كه ثبت كرده": "registered_by",

    "نوع پست": "substation_type",
    "گزارش دهنده": "reporter",
    "کاربر ثبت کننده": "created_by",

    "GISCODE پست توزیع": "distribution_gis",
    "GISCODE فیدر فشار متوسط": "mv_feeder_gis"
}


df_reference = df_reference.rename(
    columns=rename_map
)


print("Shape:")
print(df_reference.shape)


print("\nColumns:")
print(df_reference.columns.tolist())

Shape:
(2764, 49)

Columns:
['row_id', 'reported_weekday_name', 'event_id', 'region', 'report_date', 'report_time', 'mv_feeder', 'mv_feeder_code', 'distribution_substation', 'lv_feeder', 'address', 'voltage_level', 'outage_group', 'outage_reason', 'fault_type', 'fault_reason', 'initial_current', 'interrupted_load_mwh', 'energy_not_supplied_kwh', 'outage_duration', 'switch_device', 'outage_type', 'outage_scope', 'zone', 'incident_description', 'outage_start', 'outage_end', 'outage_minutes', 'registered_by', 'substation_type', 'reporter', 'created_by', 'distribution_gis', 'mv_feeder_gis', 'source_file', 'failure_target', 'date_gregorian', 'datetime', 'gregorian_year', 'gregorian_month', 'gregorian_day', 'hour', 'weekday', 'iran_weekday', 'iran_weekday_name', 'jalali_year', 'jalali_month', 'jalali_day', 'jalali_season']

## Rename Columns

This step converts Persian column names into clear English names.

Purpose:
- Make feature engineering easier.
- Avoid errors caused by Persian column names.
- Prepare the dataset for ML/DL pipelines.

No data values are changed; only column names are renamed.

## Daily Feeder Aggregation Strategy

The original outage dataset contains event-level records (one row = one outage event).
To create a feeder-day health dataset, outage events occurring on the same feeder and the same day are aggregated.

Different aggregation methods are selected based on the physical meaning of each feature:

| Feature | Aggregation Method | Meaning in Daily Feeder Health Dataset |
|---|---|---|
| unplanned_failures | SUM | Total number of unexpected failures occurring on the feeder during the day. Represents failure frequency. |
| total_outages | COUNT | Total number of outage events recorded during the day (planned + unplanned). Represents overall outage activity. |
| planned_outages | Conditional SUM | Number of planned outages during the day. Separates maintenance activity from unexpected failures. |
| total_duration | SUM | Total interruption time accumulated during the day. Represents overall outage burden. |
| max_duration | MAX | Duration of the most severe single outage event. Captures extreme outage severity. |
| total_energy_loss | SUM | Total energy not supplied during the day. Represents cumulative customer impact. |
| max_energy_loss | MAX | Highest energy loss caused by a single outage event. Identifies extreme impact events. |
| average_current | MEAN | Average interrupted current level across outage events. Represents typical electrical stress. |
| max_interrupted_load | MAX | Maximum interrupted load among events. Captures peak network impact. |
| switching_events | COUNT | Number of outage records with a recorded switching device. Represents operational activity. |

Aggregation principle:

- **SUM** → used for cumulative effects (failures, duration, energy loss).
- **MAX** → used for extreme events (worst outage severity and impact).
- **MEAN** → used for continuous measurements where the average condition is meaningful.
- **COUNT** → used for event frequency and operational activity.

Keeping both cumulative and extreme indicators allows the model to distinguish between:

- feeders with frequent small disturbances,
- feeders with rare but highly damaging failures.

In [10]:
# ==========================================
# Daily Numerical Feeder Aggregation
# ==========================================

import pandas as pd


# ------------------------------------------
# 1. Create daily date
# ------------------------------------------

df_reference["date"] = (
    df_reference["datetime"]
    .dt.normalize()
)


# ------------------------------------------
# 2. Separate planned / unplanned impact
# ------------------------------------------

df_reference["unplanned_duration"] = (
    df_reference["outage_minutes"]
    .where(
        df_reference["failure_target"] == 1,
        0
    )
)

df_reference["planned_duration"] = (
    df_reference["outage_minutes"]
    .where(
        df_reference["failure_target"] == 0,
        0
    )
)


df_reference["unplanned_energy_loss"] = (
    df_reference["energy_not_supplied_kwh"]
    .where(
        df_reference["failure_target"] == 1,
        0
    )
)

df_reference["planned_energy_loss"] = (
    df_reference["energy_not_supplied_kwh"]
    .where(
        df_reference["failure_target"] == 0,
        0
    )
)


# ------------------------------------------
# 3. Daily numerical aggregation
# ------------------------------------------

daily_numeric = (
    df_reference
    .groupby(
        [
            "mv_feeder_gis",
            "date"
        ]
    )
    .agg(

        # Failure frequency
        unplanned_failures=(
            "failure_target",
            "sum"
        ),

        total_outages=(
            "failure_target",
            "count"
        ),

        planned_outages=(
            "failure_target",
            lambda x: (x == 0).sum()
        ),


        # Duration
        total_duration=(
            "outage_minutes",
            "sum"
        ),

        unplanned_duration=(
            "unplanned_duration",
            "sum"
        ),

        planned_duration=(
            "planned_duration",
            "sum"
        ),

        max_duration=(
            "outage_minutes",
            "max"
        ),


        # Energy
        total_energy_loss=(
            "energy_not_supplied_kwh",
            "sum"
        ),

        unplanned_energy_loss=(
            "unplanned_energy_loss",
            "sum"
        ),

        planned_energy_loss=(
            "planned_energy_loss",
            "sum"
        ),

        max_energy_loss=(
            "energy_not_supplied_kwh",
            "max"
        ),


        # Electrical stress
        average_current=(
            "initial_current",
            "mean"
        ),

        max_interrupted_load=(
            "interrupted_load_mwh",
            "max"
        ),


        # Operational activity
        switching_events=(
            "switch_device",
            "count"
        )

    )
    .reset_index()
)


print("Daily numerical dataset shape:")
print(daily_numeric.shape)

display(
    daily_numeric.head()
)

Daily numerical dataset shape:
(2036, 16)

,mv_feeder_gis,date,unplanned_failures,total_outages,planned_outages,total_duration,unplanned_duration,planned_duration,max_duration,total_energy_loss,unplanned_energy_loss,planned_energy_loss,max_energy_loss,average_current,max_interrupted_load,switching_events
0,112240,2016-03-24,1,1,0,36,36,0,36,16.750440,16.750440,0.000000,16.750440,79.0,0.027917,1
1,112240,2016-03-29,1,1,0,70,70,0,70,84.277742,84.277742,0.000000,84.277742,2.0,0.058824,1
2,112240,2016-04-05,1,1,0,47,47,0,47,5.867878,5.867878,0.000000,5.867878,70.0,0.007491,1
3,112240,2016-04-06,0,1,1,20,0,20,20,8.471666,0.000000,8.471666,8.471666,87.0,0.025415,1
4,112240,2016-04-15,1,1,0,139,139,0,139,51.703025,51.703025,0.000000,51.703025,79.0,0.022318,1

In [11]:
# ==========================================
# Sort feeder history chronologically
# ==========================================

daily_numeric = (
    daily_numeric
    .sort_values(
        [
            "mv_feeder_gis",
            "date"
        ]
    )
    .reset_index(drop=True)
)


print("Sorted successfully.")

display(
    daily_numeric.head()
)

Sorted successfully.

,mv_feeder_gis,date,unplanned_failures,total_outages,planned_outages,total_duration,unplanned_duration,planned_duration,max_duration,total_energy_loss,unplanned_energy_loss,planned_energy_loss,max_energy_loss,average_current,max_interrupted_load,switching_events
0,112240,2016-03-24,1,1,0,36,36,0,36,16.750440,16.750440,0.000000,16.750440,79.0,0.027917,1
1,112240,2016-03-29,1,1,0,70,70,0,70,84.277742,84.277742,0.000000,84.277742,2.0,0.058824,1
2,112240,2016-04-05,1,1,0,47,47,0,47,5.867878,5.867878,0.000000,5.867878,70.0,0.007491,1
3,112240,2016-04-06,0,1,1,20,0,20,20,8.471666,0.000000,8.471666,8.471666,87.0,0.025415,1
4,112240,2016-04-15,1,1,0,139,139,0,139,51.703025,51.703025,0.000000,51.703025,79.0,0.022318,1

## Chronological Sorting

The daily feeder dataset is sorted by feeder identity and date.

This ensures that each feeder's historical records are in the correct temporal order before creating time-series sequences for LSTM modeling.

Sorting by:
- mv_feeder_gis → keeps each feeder history together.
- date → preserves chronological order.

##**Checkups**

**Check static feature consistency**

In [12]:
# ==========================================
# Check feeder identity consistency
# ==========================================

check_cols = [
    "mv_feeder_code",
    "mv_feeder",
    "region"
]


variation_check = (
    df_reference
    .groupby("mv_feeder_gis")[check_cols]
    .nunique()
)


display(variation_check)


print("Feeders with changing information:")

display(
    variation_check[
        (variation_check > 1).any(axis=1)
    ]
)

               mv_feeder_code  mv_feeder  region
mv_feeder_gis
112240                      1          1       2
112260                      1          1       2
112280                      1          1       1
112320                      1          1       1

Feeders with changing information:

               mv_feeder_code  mv_feeder  region
mv_feeder_gis
112240                      1          1       2
112260                      1          1       2

In [13]:
# ==========================================
# Build Complete Daily Feeder Dataset
# ==========================================

import pandas as pd
from persiantools.jdatetime import JalaliDate


# ==========================================
# 1. Preserve feeder identity information
# ==========================================

# These were already confirmed to be constant
# within each MV feeder.

feeder_info = (
    df_reference
    .groupby("mv_feeder_gis")
    .agg(
        mv_feeder_code=("mv_feeder_code", "first"),
        mv_feeder=("mv_feeder", "first")
    )
    .reset_index()
)


# ==========================================
# 2. Preserve dynamic categorical/network data
# ==========================================

network_cols = [
    "region",
    "zone",
    "distribution_substation",
    "distribution_gis",
    "substation_type",
    "voltage_level",
    "lv_feeder"
]


# Keep every unique value observed in a feeder-day
# without one-hot / multi-hot encoding.

def combine_unique_values(series):

    values = (
        series
        .dropna()
        .astype(str)
        .str.strip()
    )

    values = [
        value
        for value in pd.unique(values)
        if value != ""
    ]

    if len(values) == 0:
        return pd.NA

    return " | ".join(values)


daily_network = (
    df_reference
    .groupby(
        [
            "mv_feeder_gis",
            "date"
        ]
    )[network_cols]
    .agg(combine_unique_values)
    .reset_index()
)


print("Daily network dataset shape:")
print(daily_network.shape)

display(daily_network.head())

Daily network dataset shape:
(2036, 9)

,mv_feeder_gis,date,region,zone,distribution_substation,distribution_gis,substation_type,voltage_level,lv_feeder
0,112240,2016-03-24,پاسداران,<NA>,همیشه بهار,E914@GP13130000C9BB,زمینی,فشار ضعیف,3.0
1,112240,2016-03-29,پاسداران,<NA>,دشتستان6,E914@00000SP40041,هوایی,فشار متوسط,<NA>
2,112240,2016-04-05,پاسداران,<NA>,برج زمرد,E914@GP13130000CBB0,زمینی,فشار ضعیف,8.0
3,112240,2016-04-06,پاسداران,<NA>,جنوب قلهک,E914@00000SB40657,زمینی,فشار ضعیف,8.0
4,112240,2016-04-15,پاسداران,<NA>,همیشه بهار,E914@GP13130000C9BB,زمینی,فشار ضعیف,3.0

In [14]:
# ============================================================
# FINAL STEP: Build and Save Complete Daily Feeder Dataset
# ============================================================

import pandas as pd
from persiantools.jdatetime import JalaliDate


# ------------------------------------------------------------
# 1. Preserve static feeder identity
# ------------------------------------------------------------

feeder_info = (
    df_reference
    .groupby("mv_feeder_gis")
    .agg(
        mv_feeder_code=("mv_feeder_code", "first"),
        mv_feeder=("mv_feeder", "first")
    )
    .reset_index()
)


# ------------------------------------------------------------
# 2. Merge numerical + categorical/network information
# ------------------------------------------------------------

observed_daily = (
    daily_numeric
    .merge(
        daily_network,
        on=["mv_feeder_gis", "date"],
        how="left",
        validate="one_to_one"
    )
)


print("Observed feeder-days:")
print(observed_daily.shape)


# ------------------------------------------------------------
# 3. Create complete daily timeline for each feeder
# ------------------------------------------------------------

calendar_parts = []


for feeder, feeder_data in df_reference.groupby("mv_feeder_gis"):

    start_date = feeder_data["date"].min()
    end_date = feeder_data["date"].max()

    feeder_calendar = pd.DataFrame({
        "mv_feeder_gis": feeder,
        "date": pd.date_range(
            start=start_date,
            end=end_date,
            freq="D"
        )
    })

    calendar_parts.append(feeder_calendar)


full_calendar = pd.concat(
    calendar_parts,
    ignore_index=True
)


print("\nComplete calendar rows:")
print(full_calendar.shape)


# ------------------------------------------------------------
# 4. Merge observed data into complete calendar
# ------------------------------------------------------------

daily_health = (
    full_calendar
    .merge(
        observed_daily,
        on=["mv_feeder_gis", "date"],
        how="left",
        validate="one_to_one"
    )
    .merge(
        feeder_info,
        on="mv_feeder_gis",
        how="left",
        validate="many_to_one"
    )
)


# ------------------------------------------------------------
# 5. Identify true no-event days
# ------------------------------------------------------------

no_event_day = (
    daily_health["total_outages"].isna()
)


# These variables genuinely equal zero
# when there was no outage event.

zero_on_no_event_cols = [
    "unplanned_failures",
    "total_outages",
    "planned_outages",

    "total_duration",
    "unplanned_duration",
    "planned_duration",
    "max_duration",

    "total_energy_loss",
    "unplanned_energy_loss",
    "planned_energy_loss",
    "max_energy_loss",

    "max_interrupted_load",
    "switching_events"
]


daily_health.loc[
    no_event_day,
    zero_on_no_event_cols
] = 0


# Do NOT fill average_current.
# Missing means no outage-related current measurement.


# ------------------------------------------------------------
# 6. Restore integer count columns
# ------------------------------------------------------------

count_cols = [
    "unplanned_failures",
    "total_outages",
    "planned_outages",
    "switching_events"
]


daily_health[count_cols] = (
    daily_health[count_cols]
    .astype(int)
)


# ------------------------------------------------------------
# 7. Create daily binary failure indicator
# ------------------------------------------------------------

daily_health["failure_binary"] = (
    daily_health["unplanned_failures"] > 0
).astype(int)


# ------------------------------------------------------------
# 8. Gregorian calendar features
# ------------------------------------------------------------

daily_health["gregorian_year"] = (
    daily_health["date"].dt.year
)

daily_health["gregorian_month"] = (
    daily_health["date"].dt.month
)

daily_health["gregorian_day"] = (
    daily_health["date"].dt.day
)


# Pandas:
# Monday = 0 ... Sunday = 6

daily_health["weekday"] = (
    daily_health["date"].dt.weekday
)


# Iranian calendar week:
# Saturday = 0 ... Friday = 6

daily_health["iran_weekday"] = (
    (daily_health["weekday"] + 2) % 7
)


iran_weekday_names = {
    0: "Saturday",
    1: "Sunday",
    2: "Monday",
    3: "Tuesday",
    4: "Wednesday",
    5: "Thursday",
    6: "Friday"
}


daily_health["iran_weekday_name"] = (
    daily_health["iran_weekday"]
    .map(iran_weekday_names)
)


# ------------------------------------------------------------
# 9. Jalali calendar features
# ------------------------------------------------------------

def gregorian_to_jalali(date):

    try:

        date = pd.Timestamp(date)

        try:
            jdate = JalaliDate.to_jalali(
                date.year,
                date.month,
                date.day
            )

        except TypeError:
            jdate = JalaliDate.to_jalali(
                date.date()
            )

        return pd.Series([
            jdate.year,
            jdate.month,
            jdate.day
        ])

    except Exception:

        return pd.Series([
            pd.NA,
            pd.NA,
            pd.NA
        ])


daily_health[
    [
        "jalali_year",
        "jalali_month",
        "jalali_day"
    ]
] = (
    daily_health["date"]
    .apply(gregorian_to_jalali)
)


def get_jalali_season(month):

    if month in [1, 2, 3]:
        return "Spring"

    elif month in [4, 5, 6]:
        return "Summer"

    elif month in [7, 8, 9]:
        return "Autumn"

    elif month in [10, 11, 12]:
        return "Winter"

    return "Unknown"


daily_health["jalali_season"] = (
    daily_health["jalali_month"]
    .apply(get_jalali_season)
)


# ------------------------------------------------------------
# 10. Sort chronologically
# ------------------------------------------------------------

daily_health = (
    daily_health
    .sort_values(
        [
            "mv_feeder_gis",
            "date"
        ]
    )
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 11. Reorder important columns
# ------------------------------------------------------------

priority_cols = [
    "date",
    "mv_feeder_gis",
    "mv_feeder_code",
    "mv_feeder",

    "unplanned_failures",
    "failure_binary",

    "total_outages",
    "planned_outages"
]


remaining_cols = [
    col for col in daily_health.columns
    if col not in priority_cols
]


daily_health = daily_health[
    priority_cols + remaining_cols
]


# ------------------------------------------------------------
# 12. Final validation
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("FINAL DAILY DATASET CHECK")
print("=" * 60)


print("\nFinal shape:")
print(daily_health.shape)


print("\nNumber of feeders:")
print(
    daily_health["mv_feeder_gis"].nunique()
)


print("\nDuplicate feeder-days:")
print(
    daily_health
    .duplicated(
        subset=[
            "mv_feeder_gis",
            "date"
        ]
    )
    .sum()
)


print("\nDays per feeder:")
display(
    daily_health
    .groupby("mv_feeder_gis")["date"]
    .count()
)


print("\nNo-event days:")
print(
    (
        daily_health["total_outages"] == 0
    ).sum()
)


print("\nFailure days:")
print(
    daily_health["failure_binary"].sum()
)


print("\nFailure binary distribution:")
display(
    daily_health["failure_binary"]
    .value_counts()
    .sort_index()
)


print("\nDate range:")
print(
    daily_health["date"].min(),
    "to",
    daily_health["date"].max()
)


network_cols = [
    "region",
    "zone",
    "distribution_substation",
    "distribution_gis",
    "substation_type",
    "voltage_level",
    "lv_feeder"
]


print("\nNetwork columns preserved:")

for col in network_cols:

    print(
        col,
        "✓" if col in daily_health.columns
        else "MISSING"
    )


print("\nMissing Jalali dates:")
print(
    daily_health["jalali_year"]
    .isna()
    .sum()
)


display(
    daily_health.head(10)
)


# ------------------------------------------------------------
# 13. Save final CSV
# ------------------------------------------------------------

output_path = "/content/daily_feeder_health(II).csv"


daily_health.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig",
    date_format="%Y-%m-%d"
)


print("\nSaved successfully:")
print(output_path)

Observed feeder-days:
(2036, 23)

Complete calendar rows:
(13798, 2)

============================================================
FINAL DAILY DATASET CHECK
============================================================

Final shape:
(13798, 36)

Number of feeders:
4

Duplicate feeder-days:
0

Days per feeder:

mv_feeder_gis
112240    3468
112260    3441
112280    3436
112320    3453
Name: date, dtype: int64

No-event days:
11762

Failure days:
1486

Failure binary distribution:

failure_binary
0    12312
1     1486
Name: count, dtype: int64

Date range:
2016-03-24 00:00:00 to 2025-09-20 00:00:00

Network columns preserved:
region ✓
zone ✓
distribution_substation ✓
distribution_gis ✓
substation_type ✓
voltage_level ✓
lv_feeder ✓

Missing Jalali dates:
0

,date,mv_feeder_gis,mv_feeder_code,mv_feeder,unplanned_failures,failure_binary,total_outages,planned_outages,total_duration,unplanned_duration,...,gregorian_year,gregorian_month,gregorian_day,weekday,iran_weekday,iran_weekday_name,jalali_year,jalali_month,jalali_day,jalali_season
0,2016-03-24,112240,25794022,MV_شریعتی_زمرد,1,1,1,0,36.0,36.0,...,2016,3,24,3,5,Thursday,1395,1,5,Spring
1,2016-03-25,112240,25794022,MV_شریعتی_زمرد,0,0,0,0,0.0,0.0,...,2016,3,25,4,6,Friday,1395,1,6,Spring
2,2016-03-26,112240,25794022,MV_شریعتی_زمرد,0,0,0,0,0.0,0.0,...,2016,3,26,5,0,Saturday,1395,1,7,Spring
3,2016-03-27,112240,25794022,MV_شریعتی_زمرد,0,0,0,0,0.0,0.0,...,2016,3,27,6,1,Sunday,1395,1,8,Spring
4,2016-03-28,112240,25794022,MV_شریعتی_زمرد,0,0,0,0,0.0,0.0,...,2016,3,28,0,2,Monday,1395,1,9,Spring
5,2016-03-29,112240,25794022,MV_شریعتی_زمرد,1,1,1,0,70.0,70.0,...,2016,3,29,1,3,Tuesday,1395,1,10,Spring
6,2016-03-30,112240,25794022,MV_شریعتی_زمرد,0,0,0,0,0.0,0.0,...,2016,3,30,2,4,Wednesday,1395,1,11,Spring
7,2016-03-31,112240,25794022,MV_شریعتی_زمرد,0,0,0,0,0.0,0.0,...,2016,3,31,3,5,Thursday,1395,1,12,Spring
8,2016-04-01,112240,25794022,MV_شریعتی_زمرد,0,0,0,0,0.0,0.0,...,2016,4,1,4,6,Friday,1395,1,13,Spring
9,2016-04-02,112240,25794022,MV_شریعتی_زمرد,0,0,0,0,0.0,0.0,...,2016,4,2,5,0,Saturday,1395,1,14,Spring

Saved successfully:
/content/daily_feeder_health(II).csv

## Final Daily Feeder Dataset Construction

This step builds the final daily feeder-level dataset by combining numerical health indicators with preserved network and feeder information.

Main actions:
- Merge numerical and categorical/network daily features.
- Create a complete daily timeline for each feeder.
- Set true no-event outage indicators to zero.
- Create `failure_binary` using only unplanned failures.
- Add Gregorian, Iranian weekday, and Jalali calendar features.
- Sort feeder histories chronologically.
- Validate duplicates, date coverage, feeder counts, and preserved network features.
- Save the final dataset as CSV.

The resulting dataset contains one row per feeder-day and is ready for later feature preparation and time-series modeling.

In [15]:
# ============================================================
# FINAL VALIDATION: Original Data vs Final Daily Dataset
# ============================================================

import pandas as pd
import numpy as np


print("=" * 70)
print("ORIGINAL DATA vs FINAL DAILY DATASET")
print("=" * 70)


# ------------------------------------------------------------
# 1. Basic structure
# ------------------------------------------------------------

print("\nBASIC STRUCTURE")

comparison = pd.DataFrame({

    "Original Event Data": [
        data.shape[0],
        data.shape[1],
        data["GISCODE فیدر فشار متوسط"].nunique()
    ],

    "Final Daily Data": [
        daily_health.shape[0],
        daily_health.shape[1],
        daily_health["mv_feeder_gis"].nunique()
    ]

}, index=[
    "Rows",
    "Columns",
    "MV Feeders"
])

display(comparison)


# ------------------------------------------------------------
# 2. Check outage event preservation
# ------------------------------------------------------------

original_unplanned = (
    data["نوع قطعی"]
    .eq("بی برنامه")
    .sum()
)

original_planned = (
    data["نوع قطعی"]
    .eq("با برنامه")
    .sum()
)

original_total = len(data)


final_unplanned = (
    daily_health["unplanned_failures"]
    .sum()
)

final_planned = (
    daily_health["planned_outages"]
    .sum()
)

final_total = (
    daily_health["total_outages"]
    .sum()
)


event_check = pd.DataFrame({

    "Original": [
        original_total,
        original_unplanned,
        original_planned
    ],

    "Final": [
        final_total,
        final_unplanned,
        final_planned
    ]

}, index=[
    "Total outage events",
    "Unplanned outage events",
    "Planned outage events"
])


event_check["Match"] = (
    event_check["Original"]
    == event_check["Final"]
)


print("\nOUTAGE EVENT PRESERVATION")
display(event_check)


# ------------------------------------------------------------
# 3. Check numerical aggregation preservation
# ------------------------------------------------------------

original_duration = pd.to_numeric(
    data["مدت زمان خاموشی به دقیقه"],
    errors="coerce"
).sum()

original_energy = pd.to_numeric(
    data["انرژی توزیع نشده (KWH)"],
    errors="coerce"
).sum()


final_duration = (
    daily_health["total_duration"]
    .sum()
)

final_energy = (
    daily_health["total_energy_loss"]
    .sum()
)


numeric_check = pd.DataFrame({

    "Original": [
        original_duration,
        original_energy
    ],

    "Final": [
        final_duration,
        final_energy
    ]

}, index=[
    "Total outage duration",
    "Total energy not supplied"
])


numeric_check["Match"] = [
    np.isclose(
        original_duration,
        final_duration,
        equal_nan=True
    ),

    np.isclose(
        original_energy,
        final_energy,
        equal_nan=True
    )
]


print("\nNUMERICAL AGGREGATION CHECK")
display(numeric_check)


# ------------------------------------------------------------
# 4. Final daily structure
# ------------------------------------------------------------

print("\nFINAL DAILY STRUCTURE")

print(
    "Observed outage days:",
    (daily_health["total_outages"] > 0).sum()
)

print(
    "No-event days:",
    (daily_health["total_outages"] == 0).sum()
)

print(
    "Days with unplanned failure:",
    daily_health["failure_binary"].sum()
)

print(
    "Duplicate feeder-days:",
    daily_health.duplicated(
        subset=[
            "mv_feeder_gis",
            "date"
        ]
    ).sum()
)


# ------------------------------------------------------------
# 5. Network feature preservation
# ------------------------------------------------------------

network_cols = [
    "region",
    "zone",
    "distribution_substation",
    "distribution_gis",
    "substation_type",
    "voltage_level",
    "lv_feeder"
]


print("\nNETWORK FEATURES")

for col in network_cols:

    print(
        f"{col}:",
        "PRESERVED ✓"
        if col in daily_health.columns
        else "MISSING ✗"
    )


# ------------------------------------------------------------
# 6. Overall validation
# ------------------------------------------------------------

all_event_checks = (
    event_check["Match"].all()
)

all_numeric_checks = (
    numeric_check["Match"].all()
)

no_duplicates = (
    daily_health
    .duplicated(
        subset=[
            "mv_feeder_gis",
            "date"
        ]
    )
    .sum()
    == 0
)


print("\n" + "=" * 70)

if (
    all_event_checks
    and all_numeric_checks
    and no_duplicates
):

    print("FINAL VALIDATION PASSED ✓")

else:

    print("FINAL VALIDATION REQUIRES REVIEW ⚠")

print("=" * 70)

======================================================================
ORIGINAL DATA vs FINAL DAILY DATASET
======================================================================

BASIC STRUCTURE

            Original Event Data  Final Daily Data
Rows                       2764             13798
Columns                      55                36
MV Feeders                    4                 4

OUTAGE EVENT PRESERVATION

                         Original  Final  Match
Total outage events          2764   2764   True
Unplanned outage events      1930   1930   True
Planned outage events         834    834   True

NUMERICAL AGGREGATION CHECK

                                Original          Final  Match
Total outage duration      174675.000000  174675.000000   True
Total energy not supplied  355151.048991  355151.048991   True

FINAL DAILY STRUCTURE
Observed outage days: 2036
No-event days: 11762
Days with unplanned failure: 1486
Duplicate feeder-days: 0

NETWORK FEATURES
region: PRESERVED ✓
zone: PRESERVED ✓
distribution_substation: PRESERVED ✓
distribution_gis: PRESERVED ✓
substation_type: PRESERVED ✓
voltage_level: PRESERVED ✓
lv_feeder: PRESERVED ✓

======================================================================
FINAL VALIDATION PASSED ✓
======================================================================

## From Raw Event Data to Final Daily Feeder Dataset

The original dataset contained **2,764 individual outage events and 55 columns**. During preprocessing, it was transformed into a structured daily time-series dataset with **13,798 feeder-days and 36 columns**.

Main transformations:

- Removed completely empty and constant columns.
- Normalized Persian text and handled missing values.
- Created the unplanned outage target (`failure_target`).
- Converted Jalali dates to Gregorian datetime and generated calendar features.
- Renamed variables to clear English names.
- Aggregated individual outage events into one record per **feeder-day**.
- Created daily numerical indicators such as outage counts, duration, energy loss, and electrical stress.
- Preserved important network information such as region, zone, substations, voltage level, and LV feeder without one-hot encoding.
- Created a complete daily timeline, adding days with no recorded outage.
- Created `failure_binary`, where **1 means at least one unplanned failure occurred that day**.
- Added Gregorian, Jalali, and Iranian weekday features.
- Sorted and validated the final time series.

Therefore, the number of rows increased because missing calendar days were added, while the number of columns decreased because irrelevant, empty, constant, administrative, and event-level fields were removed or summarized into meaningful daily features.

The final dataset is a validated daily feeder-health time series suitable for the next modeling stage.

In [17]:
# ============================================================
# FINAL COLUMN AUDIT
# Original Dataset vs Final Daily Dataset
# ============================================================

import pandas as pd


# ------------------------------------------------------------
# 1. Normalize column names for reliable matching
# ------------------------------------------------------------

def normalize_name(name):

    name = str(name)

    return (
        name
        .replace("ي", "ی")
        .replace("ى", "ی")
        .replace("ك", "ک")
        .replace("ۀ", "ه")
        .strip()
    )


def normalize_dict_keys(dictionary):

    return {
        normalize_name(key): value
        for key, value in dictionary.items()
    }


# ------------------------------------------------------------
# 2. Original → preserved final columns
# ------------------------------------------------------------

preserved_map = normalize_dict_keys({

    "منطقه اصلی": "region",

    "فیدر فشار متوسط": "mv_feeder",
    "کد فیدر فشار متوسط": "mv_feeder_code",
    "GISCODE فیدر فشار متوسط": "mv_feeder_gis",

    "پست توزیع": "distribution_substation",
    "GISCODE پست توزیع": "distribution_gis",

    "فیدر فشار ضعیف": "lv_feeder",
    "سطح ولتاژ": "voltage_level",

    "نوع پست": "substation_type",
    "زون": "zone"
})


# ------------------------------------------------------------
# 3. Original → transformed / aggregated columns
# ------------------------------------------------------------

transformed_map = normalize_dict_keys({

    "تاریخ اطلاع": (
        "date + calendar features",
        "Converted to daily Gregorian/Jalali calendar information"
    ),

    "ساعت اطلاع": (
        "Not directly retained",
        "Used to construct event datetime before daily aggregation"
    ),

    "روز هفته": (
        "weekday, iran_weekday, iran_weekday_name",
        "Recreated from the final daily date"
    ),

    "نوع قطعی": (
        "unplanned_failures, planned_outages, failure_binary",
        "Used to distinguish planned and unplanned outages"
    ),

    "مدت زمان خاموشی به دقیقه": (
        "total_duration, unplanned_duration, planned_duration, max_duration",
        "Aggregated by feeder-day"
    ),

    "انرژی توزیع نشده (KWH)": (
        "total_energy_loss, unplanned_energy_loss, planned_energy_loss, max_energy_loss",
        "Aggregated by feeder-day"
    ),

    "جریان قطع اولیه": (
        "average_current",
        "Daily mean of available outage-current measurements"
    ),

    "بار قطع شده (MWH)": (
        "max_interrupted_load",
        "Daily maximum interrupted load"
    ),

    "جداکننده": (
        "switching_events",
        "Counted by feeder-day"
    )
})


# ------------------------------------------------------------
# 4. Original columns intentionally not carried forward
# ------------------------------------------------------------

not_carried_notes = normalize_dict_keys({

    "ردیف":
        "Administrative row identifier",

    "ردیف یکتا":
        "Event-level identifier",

    "آدرس":
        "High-cardinality event-level location text",

    "گروه قطع":
        "Event-level outage information not used in current daily feature set",

    "علت قطع":
        "Event-level outage reason not used in current daily feature set",

    "اشکال":
        "Event-level fault information not used in current daily feature set",

    "علت اشکال":
        "Event-level fault detail not used in current daily feature set",

    "مدت قطع":
        "Not used; outage_minutes was used for daily duration",

    "تکی یا کلی به تشخیص اپراتور":
        "Event-level outage scope",

    "شرح حادثه":
        "Free-text event description",

    "زمان قطع":
        "Event-level outage timestamp",

    "زمان وصل":
        "Event-level restoration timestamp",

    "كاربري كه ثبت كرده":
        "Administrative user information",

    "گزارش دهنده":
        "Reporting information",

    "کاربر ثبت کننده":
        "Administrative user information",

    "source_file":
        "Source-file provenance only"
})


# ------------------------------------------------------------
# 5. Detect columns actually removed during Step 2
# ------------------------------------------------------------

cleaned_names = {
    normalize_name(col)
    for col in df_clean.columns
}


removed_names = {
    normalize_name(col)
    for col in data.columns
    if normalize_name(col) not in cleaned_names
}


# Determine whether removed column was empty or constant
removed_reasons = {}


for col in data.columns:

    key = normalize_name(col)

    if key not in removed_names:
        continue

    series = data[col].copy()

    if series.dtype == "object":

        series = (
            series
            .astype("string")
            .str.strip()
            .replace(r"^\s*$", pd.NA, regex=True)
        )

    if series.isna().all():

        removed_reasons[key] = "Completely empty"

    elif series.nunique(dropna=True) <= 1:

        removed_reasons[key] = "Constant column"

    else:

        removed_reasons[key] = "Removed during basic cleaning"


# ------------------------------------------------------------
# 6. Build ORIGINAL column audit
# ------------------------------------------------------------

network_original_cols = {
    normalize_name(x)
    for x in [
        "منطقه اصلی",
        "پست توزیع",
        "GISCODE پست توزیع",
        "فیدر فشار ضعیف",
        "سطح ولتاژ",
        "نوع پست",
        "زون"
    ]
}


original_audit = []


for original_col in data.columns:

    key = normalize_name(original_col)


    if key in removed_names:

        status = "REMOVED"
        final_representation = "-"
        note = removed_reasons[key]


    elif key in preserved_map:

        status = "PRESERVED / RENAMED"
        final_representation = preserved_map[key]

        if key in network_original_cols:

            note = (
                "Preserved as daily network information; "
                "multiple same-day values may be combined"
            )

        else:

            note = "Preserved as feeder identity information"


    elif key in transformed_map:

        status = "TRANSFORMED / AGGREGATED"
        final_representation = transformed_map[key][0]
        note = transformed_map[key][1]


    elif key in not_carried_notes:

        status = "NOT CARRIED TO FINAL"
        final_representation = "-"
        note = not_carried_notes[key]


    else:

        status = "REVIEW"
        final_representation = "-"
        note = "No transformation rule found"


    original_audit.append({

        "Original Column": original_col,
        "Status": status,
        "Final Representation": final_representation,
        "Brief Explanation": note

    })


original_audit = pd.DataFrame(original_audit)


# ------------------------------------------------------------
# 7. Define lineage of every FINAL column
# ------------------------------------------------------------

final_lineage = {

    "date":
        ("DERIVED", "تاریخ اطلاع",
         "Gregorian daily date and complete calendar"),

    "mv_feeder_gis":
        ("PRESERVED / RENAMED", "GISCODE فیدر فشار متوسط",
         "Main feeder identifier"),

    "mv_feeder_code":
        ("PRESERVED / RENAMED", "کد فیدر فشار متوسط",
         "Static feeder code"),

    "mv_feeder":
        ("PRESERVED / RENAMED", "فیدر فشار متوسط",
         "Static feeder name"),

    "unplanned_failures":
        ("AGGREGATED", "نوع قطعی",
         "Number of unplanned outage events per feeder-day"),

    "failure_binary":
        ("DERIVED", "unplanned_failures",
         "1 if at least one unplanned failure occurred"),

    "total_outages":
        ("AGGREGATED", "All outage records",
         "Total outage events per feeder-day"),

    "planned_outages":
        ("AGGREGATED", "نوع قطعی",
         "Number of planned outages per feeder-day"),

    "total_duration":
        ("AGGREGATED", "مدت زمان خاموشی به دقیقه",
         "Total outage duration"),

    "unplanned_duration":
        ("AGGREGATED", "مدت زمان خاموشی به دقیقه + نوع قطعی",
         "Total unplanned outage duration"),

    "planned_duration":
        ("AGGREGATED", "مدت زمان خاموشی به دقیقه + نوع قطعی",
         "Total planned outage duration"),

    "max_duration":
        ("AGGREGATED", "مدت زمان خاموشی به دقیقه",
         "Maximum outage duration"),

    "total_energy_loss":
        ("AGGREGATED", "انرژی توزیع نشده (KWH)",
         "Total daily energy not supplied"),

    "unplanned_energy_loss":
        ("AGGREGATED", "انرژی توزیع نشده (KWH) + نوع قطعی",
         "Unplanned-outage energy loss"),

    "planned_energy_loss":
        ("AGGREGATED", "انرژی توزیع نشده (KWH) + نوع قطعی",
         "Planned-outage energy loss"),

    "max_energy_loss":
        ("AGGREGATED", "انرژی توزیع نشده (KWH)",
         "Maximum event energy loss"),

    "average_current":
        ("AGGREGATED", "جریان قطع اولیه",
         "Mean outage-related current"),

    "max_interrupted_load":
        ("AGGREGATED", "بار قطع شده (MWH)",
         "Maximum interrupted load"),

    "switching_events":
        ("AGGREGATED", "جداکننده",
         "Number of non-missing switching-device records"),

    "region":
        ("PRESERVED / DAILY", "منطقه اصلی",
         "Region values observed during feeder-day"),

    "zone":
        ("PRESERVED / DAILY", "زون",
         "Zone values observed during feeder-day"),

    "distribution_substation":
        ("PRESERVED / DAILY", "پست توزیع",
         "Distribution substations observed during feeder-day"),

    "distribution_gis":
        ("PRESERVED / DAILY", "GISCODE پست توزیع",
         "Distribution GIS assets observed during feeder-day"),

    "substation_type":
        ("PRESERVED / DAILY", "نوع پست",
         "Substation types observed during feeder-day"),

    "voltage_level":
        ("PRESERVED / DAILY", "سطح ولتاژ",
         "Voltage levels observed during feeder-day"),

    "lv_feeder":
        ("PRESERVED / DAILY", "فیدر فشار ضعیف",
         "LV feeders observed during feeder-day"),

    "gregorian_year":
        ("DERIVED", "date", "Gregorian year"),

    "gregorian_month":
        ("DERIVED", "date", "Gregorian month"),

    "gregorian_day":
        ("DERIVED", "date", "Gregorian day"),

    "weekday":
        ("DERIVED", "date", "Pandas weekday: Monday=0"),

    "iran_weekday":
        ("DERIVED", "date", "Iranian weekday: Saturday=0"),

    "iran_weekday_name":
        ("DERIVED", "date", "Iranian weekday name"),

    "jalali_year":
        ("DERIVED", "date", "Jalali year"),

    "jalali_month":
        ("DERIVED", "date", "Jalali month"),

    "jalali_day":
        ("DERIVED", "date", "Jalali day"),

    "jalali_season":
        ("DERIVED", "jalali_month", "Jalali season")
}


# ------------------------------------------------------------
# 8. Build FINAL column audit
# ------------------------------------------------------------

final_audit = []


for col in daily_health.columns:

    if col in final_lineage:

        status, source, explanation = final_lineage[col]

    else:

        status = "REVIEW"
        source = "Unknown"
        explanation = "No lineage rule found"


    final_audit.append({

        "Final Column": col,
        "Status": status,
        "Source": source,
        "Brief Explanation": explanation

    })


final_audit = pd.DataFrame(final_audit)


# ------------------------------------------------------------
# 9. Display complete audits
# ------------------------------------------------------------

print("=" * 80)
print("ORIGINAL DATASET COLUMN AUDIT")
print("=" * 80)

print(f"\nOriginal columns: {len(data.columns)}")

display(original_audit)


print("\n" + "=" * 80)
print("FINAL DAILY DATASET COLUMN AUDIT")
print("=" * 80)

print(f"\nFinal columns: {len(daily_health.columns)}")

display(final_audit)


# ------------------------------------------------------------
# 10. Status summaries
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("ORIGINAL COLUMN STATUS SUMMARY")
print("=" * 80)

display(
    original_audit["Status"]
    .value_counts()
    .rename_axis("Status")
    .reset_index(name="Number of Columns")
)


print("\n" + "=" * 80)
print("FINAL COLUMN STATUS SUMMARY")
print("=" * 80)

display(
    final_audit["Status"]
    .value_counts()
    .rename_axis("Status")
    .reset_index(name="Number of Columns")
)


# ------------------------------------------------------------
# 11. Final safety check
# ------------------------------------------------------------

original_review = (
    original_audit["Status"]
    .eq("REVIEW")
    .sum()
)

final_review = (
    final_audit["Status"]
    .eq("REVIEW")
    .sum()
)


print("\n" + "=" * 80)

if original_review == 0 and final_review == 0:

    print("COLUMN AUDIT COMPLETE ✓")
    print("Every original and final column has been accounted for.")

else:

    print("COLUMN AUDIT NEEDS REVIEW ⚠")
    print("Unclassified original columns:", original_review)
    print("Unclassified final columns:", final_review)

print("=" * 80)

================================================================================
ORIGINAL DATASET COLUMN AUDIT
================================================================================

Original columns: 55

,Original Column,Status,Final Representation,Brief Explanation
0,ردیف,NOT CARRIED TO FINAL,-,Administrative row identifier
1,روز هفته,TRANSFORMED / AGGREGATED,"weekday, iran_weekday, iran_weekday_name",Recreated from the final daily date
2,ردیف یکتا,NOT CARRIED TO FINAL,-,Event-level identifier
3,معاونت,REMOVED,-,Constant column
4,منطقه اصلی,PRESERVED / RENAMED,region,Preserved as daily network information; multip...
5,تاریخ اطلاع,TRANSFORMED / AGGREGATED,date + calendar features,Converted to daily Gregorian/Jalali calendar i...
6,ساعت اطلاع,TRANSFORMED / AGGREGATED,Not directly retained,Used to construct event datetime before daily ...
7,پست فوق توزیع,REMOVED,-,Constant column
8,کد پست فوق توزیع,REMOVED,-,Constant column
9,فیدر فشار متوسط,PRESERVED / RENAMED,mv_feeder,Preserved as feeder identity information
10,کد فیدر فشار متوسط,PRESERVED / RENAMED,mv_feeder_code,Preserved as feeder identity information
11,پست توزیع,PRESERVED / RENAMED,distribution_substation,Preserved as daily network information; multip...
12,کد پست توزیع,REMOVED,-,Completely empty
13,فیدر فشار ضعیف,PRESERVED / RENAMED,lv_feeder,Preserved as daily network information; multip...
14,آدرس,NOT CARRIED TO FINAL,-,High-cardinality event-level location text
15,سطح ولتاژ,PRESERVED / RENAMED,voltage_level,Preserved as daily network information; multip...
16,گروه قطع,NOT CARRIED TO FINAL,-,Event-level outage information not used in cur...
17,علت قطع,NOT CARRIED TO FINAL,-,Event-level outage reason not used in current ...
18,اشکال,NOT CARRIED TO FINAL,-,Event-level fault information not used in curr...
19,علت اشکال,NOT CARRIED TO FINAL,-,Event-level fault detail not used in current d...
20,جریان قطع اولیه,TRANSFORMED / AGGREGATED,average_current,Daily mean of available outage-current measure...
21,بار قطع شده (MWH),TRANSFORMED / AGGREGATED,max_interrupted_load,Daily maximum interrupted load
22,انرژی توزیع نشده (KWH),TRANSFORMED / AGGREGATED,"total_energy_loss, unplanned_energy_loss, plan...",Aggregated by feeder-day
23,مدت قطع,NOT CARRIED TO FINAL,-,Not used; outage_minutes was used for daily du...
24,جداکننده,TRANSFORMED / AGGREGATED,switching_events,Counted by feeder-day
25,نوع قطعی,TRANSFORMED / AGGREGATED,"unplanned_failures, planned_outages, failure_b...",Used to distinguish planned and unplanned outages
26,وضعیت محل,REMOVED,-,Constant column
27,مامور حوادث1,REMOVED,-,Completely empty
28,نوع بابرنامه,REMOVED,-,Completely empty
29,تکی یا کلی به تشخیص اپراتور,NOT CARRIED TO FINAL,-,Event-level outage scope
30,مامورحوادث2,REMOVED,-,Completely empty
31,زون,PRESERVED / RENAMED,zone,Preserved as daily network information; multip...
32,منطقه 2,REMOVED,-,Completely empty
33,شرح حادثه,NOT CARRIED TO FINAL,-,Free-text event description
34,اطلاعات,REMOVED,-,Completely empty
35,زمان قطع,NOT CARRIED TO FINAL,-,Event-level outage timestamp
36,زمان وصل,NOT CARRIED TO FINAL,-,Event-level restoration timestamp
37,مدت زمان خاموشی به دقیقه,TRANSFORMED / AGGREGATED,"total_duration, unplanned_duration, planned_du...",Aggregated by feeder-day
38,كاربري كه ثبت كرده,NOT CARRIED TO FINAL,-,Administrative user information
39,نوع پست,PRESERVED / RENAMED,substation_type,Preserved as daily network information; multip...
40,نام پیمانکار,REMOVED,-,Completely empty
41,تلفن پیمانکار,REMOVED,-,Completely empty
42,مجموع تعداد کلیدزنی,REMOVED,-,Constant column
43,گزارش دهنده,NOT CARRIED TO FINAL,-,Reporting information
44,نوع سایر,REMOVED,-,Completely empty
45,گزارش کار اکیپ,REMOVED,-,Completely empty
46,اجازه کار,REMOVED,-,Completely empty
47,موقعیت خطا,REMOVED,-,Completely empty
48,شرح موقعیت خطا,REMOVED,-,Completely empty
49,کاربر ثبت کننده,NOT CARRIED TO FINAL,-,Administrative user information
50,ترانس MV,REMOVED,-,Completely empty
51,ترانس LV,REMOVED,-,Completely empty
52,GISCODE پست توزیع,PRESERVED / RENAMED,distribution_gis,Preserved as daily network information; multip...
53,GISCODE فیدر فشار متوسط,PRESERVED / RENAMED,mv_feeder_gis,Preserved as feeder identity information
54,source_file,NOT CARRIED TO FINAL,-,Source-file provenance only

================================================================================
FINAL DAILY DATASET COLUMN AUDIT
================================================================================

Final columns: 36

,Final Column,Status,Source,Brief Explanation
0,date,DERIVED,تاریخ اطلاع,Gregorian daily date and complete calendar
1,mv_feeder_gis,PRESERVED / RENAMED,GISCODE فیدر فشار متوسط,Main feeder identifier
2,mv_feeder_code,PRESERVED / RENAMED,کد فیدر فشار متوسط,Static feeder code
3,mv_feeder,PRESERVED / RENAMED,فیدر فشار متوسط,Static feeder name
4,unplanned_failures,AGGREGATED,نوع قطعی,Number of unplanned outage events per feeder-day
5,failure_binary,DERIVED,unplanned_failures,1 if at least one unplanned failure occurred
6,total_outages,AGGREGATED,All outage records,Total outage events per feeder-day
7,planned_outages,AGGREGATED,نوع قطعی,Number of planned outages per feeder-day
8,total_duration,AGGREGATED,مدت زمان خاموشی به دقیقه,Total outage duration
9,unplanned_duration,AGGREGATED,مدت زمان خاموشی به دقیقه + نوع قطعی,Total unplanned outage duration
10,planned_duration,AGGREGATED,مدت زمان خاموشی به دقیقه + نوع قطعی,Total planned outage duration
11,max_duration,AGGREGATED,مدت زمان خاموشی به دقیقه,Maximum outage duration
12,total_energy_loss,AGGREGATED,انرژی توزیع نشده (KWH),Total daily energy not supplied
13,unplanned_energy_loss,AGGREGATED,انرژی توزیع نشده (KWH) + نوع قطعی,Unplanned-outage energy loss
14,planned_energy_loss,AGGREGATED,انرژی توزیع نشده (KWH) + نوع قطعی,Planned-outage energy loss
15,max_energy_loss,AGGREGATED,انرژی توزیع نشده (KWH),Maximum event energy loss
16,average_current,AGGREGATED,جریان قطع اولیه,Mean outage-related current
17,max_interrupted_load,AGGREGATED,بار قطع شده (MWH),Maximum interrupted load
18,switching_events,AGGREGATED,جداکننده,Number of non-missing switching-device records
19,region,PRESERVED / DAILY,منطقه اصلی,Region values observed during feeder-day
20,zone,PRESERVED / DAILY,زون,Zone values observed during feeder-day
21,distribution_substation,PRESERVED / DAILY,پست توزیع,Distribution substations observed during feede...
22,distribution_gis,PRESERVED / DAILY,GISCODE پست توزیع,Distribution GIS assets observed during feeder...
23,substation_type,PRESERVED / DAILY,نوع پست,Substation types observed during feeder-day
24,voltage_level,PRESERVED / DAILY,سطح ولتاژ,Voltage levels observed during feeder-day
25,lv_feeder,PRESERVED / DAILY,فیدر فشار ضعیف,LV feeders observed during feeder-day
26,gregorian_year,DERIVED,date,Gregorian year
27,gregorian_month,DERIVED,date,Gregorian month
28,gregorian_day,DERIVED,date,Gregorian day
29,weekday,DERIVED,date,Pandas weekday: Monday=0
30,iran_weekday,DERIVED,date,Iranian weekday: Saturday=0
31,iran_weekday_name,DERIVED,date,Iranian weekday name
32,jalali_year,DERIVED,date,Jalali year
33,jalali_month,DERIVED,date,Jalali month
34,jalali_day,DERIVED,date,Jalali day
35,jalali_season,DERIVED,jalali_month,Jalali season

================================================================================
ORIGINAL COLUMN STATUS SUMMARY
================================================================================

                     Status  Number of Columns
0                   REMOVED                 20
1      NOT CARRIED TO FINAL                 16
2       PRESERVED / RENAMED                 10
3  TRANSFORMED / AGGREGATED                  9

================================================================================
FINAL COLUMN STATUS SUMMARY
================================================================================

                Status  Number of Columns
0           AGGREGATED                 14
1              DERIVED                 12
2    PRESERVED / DAILY                  7
3  PRESERVED / RENAMED                  3

================================================================================
COLUMN AUDIT COMPLETE ✓
Every original and final column has been accounted for.
================================================================================